apiVersion: v1
kind: Pod
metadata:
  name: myaddressbook
  labels:
    app: web
spec:
  containers:
  - name: myabcontainer
    image: jsachdev07/addressbook:latest
---
apiVersion: v1
kind: Service
metadata:
  name: addressbook-svc
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
